# Generated by Django 5.2.8 on 2025-11-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_bricks_employee', '0002_brickloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrickAdvanceDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_bricks_employee.brickemployee')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_bricks_employee.brickpayment')),
            ],
        ),
    ]
