# Generated by Django 5.2.8 on 2025-11-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_parcels', models.PositiveIntegerField()),
                ('parcel_rate', models.PositiveIntegerField(default=500)),
                ('date_given', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WoodScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyScrapReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('parcels_received', models.PositiveIntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('scrap_advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='wood_scrapper.scrapadvance')),
            ],
        ),
        migrations.AddField(
            model_name='scrapadvance',
            name='wood_scraper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='wood_scrapper.woodscraper'),
        ),
    ]
