# Generated by Django 5.2.8 on 2025-11-17 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_employee_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyadvance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hourlyemployee',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hourlysaving',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='hourentry',
            unique_together={('employee', 'date')},
        ),
        migrations.CreateModel(
            name='HourlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourly_employee_account.hourlyemployee')),
            ],
        ),
    ]
