# Generated by Django 5.2.8 on 2025-11-20 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_employee_account', '0002_alter_hourlyadvance_date_alter_hourlyemployee_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourly_employee_account.hourlyemployee')),
            ],
        ),
    ]
