# Generated by Django 5.2.8 on 2025-11-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_employee_account', '0003_hourlyloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyAdvanceDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourly_employee_account.hourlyemployee')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hourly_employee_account.hourlypayment')),
            ],
        ),
    ]
