# Generated by Django 5.2.8 on 2025-12-13 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_employee_account', '0004_hourlyadvancededuction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyadvance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hourlyadvancededuction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hourlypayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hourlysaving',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
