# Generated by Django 5.2.8 on 2025-11-13 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_employee_address_alter_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrickRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_1000', models.DecimalField(decimal_places=2, help_text='Rate per 1000 bricks (in Rs)', max_digits=10)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BrickWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.PositiveIntegerField(help_text='Number of bricks brought')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='employee.employee')),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bricks_out.brickrate')),
            ],
        ),
    ]
