# Generated by Django 5.2.8 on 2025-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_out', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brickwork',
            name='brick_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
