# Generated by Django 5.2.8 on 2025-11-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_out', '0002_brickwork_brick_type'),
        ('employee', '0002_alter_employee_address_alter_employee_phone'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_deductions', to='employee.employee')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_deductions', to='payment.payment')),
            ],
        ),
    ]
