# Generated by Django 5.2.8 on 2025-11-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_out', '0003_advancededuction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brickrate',
            name='rate_per_1000',
            field=models.DecimalField(decimal_places=2, help_text='ہزار اِینٹوں کی قِیمت (in Rs)', max_digits=10),
        ),
    ]
