# Generated by Django 5.2.8 on 2025-12-06 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_out', '0005_brickoutloan_brickoutsaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brickoutsaving',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
