# Generated by Django 5.2.8 on 2025-11-29 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kachi_ent_bharai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KachiBrickAdvanceDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kachi_ent_bharai.kachibrickemployee')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kachi_ent_bharai.kachibrickpayment')),
            ],
        ),
    ]
