# Generated by Django 5.2.8 on 2025-11-24 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bhatta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('bhattas', models.ManyToManyField(related_name='workers', to='worker.bhatta')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('bricks_worked', models.PositiveIntegerField()),
                ('bhatta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='worker.bhatta')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='YearlySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('brick_rate_per_1000', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bricks', models.PositiveIntegerField()),
                ('total_earned', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_advance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_loan_deducted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bhatta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='worker.bhatta')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='worker.worker')),
            ],
        ),
    ]
