# Generated by Django 5.2.8 on 2025-11-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlysettlement',
            name='payment_made',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
