# Generated by Django 5.2.8 on 2025-11-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_yearlysettlement_payment_made'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deducted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='worker.loan')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_deductions', to='worker.yearlysettlement')),
            ],
        ),
    ]
