# Generated by Django 5.2.8 on 2025-11-25 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_loandeduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deducted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='worker.advance')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_deductions', to='worker.yearlysettlement')),
            ],
        ),
    ]
