# Generated by Django 5.2.8 on 2025-11-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_advancededuction'),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
