# Generated by Django 5.2.8 on 2025-11-16 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TractorEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('conductor', 'Conductor')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TractorAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='tractor_account.tractoremployee')),
            ],
        ),
        migrations.CreateModel(
            name='TractorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tractor_account.tractoremployee')),
            ],
        ),
        migrations.CreateModel(
            name='TractorTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bricks_carried', models.IntegerField(choices=[(1000, '1000 bricks'), (2000, '2000 bricks')])),
                ('trip_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conductor', models.ForeignKey(blank=True, limit_choices_to={'role': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_trips', to='tractor_account.tractoremployee')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to='tractor_account.tractoremployee')),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='tractor_account.tractor')),
            ],
        ),
    ]
