# Generated by Django 5.2.8 on 2025-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractortrip',
            name='bricks_carried',
            field=models.IntegerField(choices=[(500, '500 bricks'), (1000, '1000 bricks'), (1500, '1500 bricks'), (2000, '2000 bricks'), (2500, '2500 bricks'), (3000, '3000 bricks'), (3500, '3500 bricks'), (4000, '4000 bricks'), (4500, '4500 bricks'), (5000, '5000 bricks')]),
        ),
    ]
