# Generated by Django 5.2.8 on 2025-11-20 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0003_customer_alter_tractortrip_bricks_carried'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractortrip',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tractor_trips', to='tractor_account.customer'),
        ),
    ]
