# Generated by Django 5.2.8 on 2025-11-20 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0004_tractortrip_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractorpayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tractor_account.customer'),
        ),
    ]
