# Generated by Django 5.2.8 on 2025-11-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0006_tractortrip_brick_rate_tractortrip_brick_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
