# Generated by Django 5.2.8 on 2025-11-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0007_customerpayment_address_customerpayment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tractorpayment',
            name='customer',
        ),
    ]
