# Generated by Django 5.2.8 on 2025-11-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0008_remove_tractorpayment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tractor_account.tractortrip'),
        ),
    ]
