# Generated by Django 5.2.8 on 2025-11-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0009_alter_customerpayment_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tractor_account.tractortrip'),
        ),
    ]
