# Generated by Django 5.2.8 on 2025-11-24 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0010_alter_customerledger_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
