# Generated by Django 5.2.8 on 2025-11-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0011_customerledger_date_customerledger_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractortrip',
            name='brick_type',
            field=models.CharField(choices=[('اَوّل', 'اَوّل'), ('بَیلی', 'بَیلی'), ('پکی بَیلی', 'پکی بَیلی'), ('کرڑی', 'کرڑی'), ('کھنگر', 'کھنگر'), ('ٹوٹا', 'ٹوٹا'), ('مِٹی', 'مِٹی')], default='A', max_length=200),
        ),
    ]
