# Generated by Django 5.2.8 on 2025-11-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0013_customeradvance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerledger',
            unique_together={('customer', 'trip')},
        ),
    ]
