# Generated by Django 5.2.8 on 2025-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0014_alter_customerledger_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
