# Generated by Django 5.2.8 on 2025-12-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tractor_account', '0016_tractorloan_tractortsaving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tractortrip',
            name='brick_type',
            field=models.CharField(choices=[('اَوّل', 'اَوّل'), ('بَیلی', 'بَیلی'), ('پکی بَیلی', 'پکی بَیلی'), ('کرڑی', 'کرڑی'), ('کھنگر', 'کھنگر'), ('ٹوٹا', 'ٹوٹا'), ('مِٹی', 'مِٹی'), ('کیری', 'کیری'), ('کچرو', 'کچرو')], default='A', max_length=200),
        ),
    ]
